#!/usr/bin/env python
import sys

i0 = len('Y Y Y Y ')

for line in sys.stdin:
    if 'FAIL' in line:
        v = line.strip().split()
        exp = v[-1]
        with open(exp + '/names') as f:
            names = [l.strip() for l in f]

        for c in range(len(line[i0:])//3):
            try:
                i = int(head[i0+3*c:i0+3*c+2])
            except ValueError:
                pass
            else:
                name = names[i-1]
                val = line[i0+3*c:i0+3*c+2]
                print '{:6s} {}'.format(name, val)
    elif line.startswith('Y Y Y Y'):
        head = line.rstrip()

