#!/usr/bin/env python
import sys
import string

sys.stdout.write('''# Gud diagnostics
# ==================
 &diagnostics_list
#
  frequency(1) = 3600.,
''')

for i in range(1,98):
    sys.stdout.write("  fields({0:2d},1) = 'TRAC{0:02d}  ',\n".format(i))

for name in [
        'PAR01   ',
        'DIC_c01 ',
        'DIC_c02 ',
        'c01_DOC ',
        'c02_DOC ',
        'c01_POC ',
        'c02_POC ',
        'PARF    ',
        'atten   ',
        'surfPAR ',
        'exfPAR  ',
        'limn01  ',
        'limp01  ',
        'limsi01 ',
        'limfe01 ',
        'limI01  ',
        'limT01  ',
        'c01_c   ',
        'c02_c   ',
        'c_c03   ',
        'c_c04   ',
        'c_DOC   ',
        'c_POC   ',
        'c_PIC   ',
        'n_DON   ',
        'n_PON   ',
        'p_DOP   ',
        'p_POP   ',
        ]:
    i += 1
    sys.stdout.write("  fields({0:2d},1) = '{1:<8s}',\n".format(i, name))

sys.stdout.write("    filename(1) = 'gud',\n")
sys.stdout.write('''#
 &

# Parameter for Diagnostics of per level statistics:
#-----------------
# for each output-stream:
#  stat_fname(n) : prefix of the output file name (only 8.c long) for
#outp.stream n
#  stat_freq(n):< 0 : write snap-shot output every |stat_freq| seconds
#               > 0 : write time-average output every stat_freq seconds
#  stat_phase(n)    : write at time = stat_phase + multiple of |stat_freq|
#  stat_region(:,n) : list of "regions" (default: 1 region only=global)
#  stat_fields(:,n) : list of diagnostics fields (8.c) (see
#"available_diagnostics.log"
#                 file for the list of all available diag. in this particular
#config)
#-----------------
 &DIAG_STATIS_PARMS
 diagst_mnc=.FALSE.,
     stat_freq(1:21)= 21*3600.,
    stat_phase(1:21)= 21*0.,
 stat_fields(1,1)= 'TRAC01  '
 stat_fields(1,2)= 'TRAC02  '
 stat_fields(1,3)= 'TRAC03  '
 stat_fields(1,4)= 'TRAC04  '
 stat_fields(1,5)= 'TRAC05  '
 stat_fields(1,6)= 'TRAC06  '
 stat_fields(1,7)= 'TRAC07  '
 stat_fields(1,8)= 'TRAC08  '
 stat_fields(1,9)= 'TRAC09  '
 stat_fields(1,10)= 'TRAC10  '
 stat_fields(1,11)= 'TRAC11  '
 stat_fields(1,12)= 'TRAC12  '
 stat_fields(1,13)= 'TRAC13  '
 stat_fields(1,14)= 'TRAC14  '
 stat_fields(1,15)= 'TRAC15  '
 stat_fields(1,16)= 'TRAC16  '
 stat_fields(1,17)= 'TRAC17  '
 stat_fields(1,18)= 'TRAC18  '
 stat_fields(1,19)= 'TRAC19  '
 stat_fields(1,20)= 'TRAC20  '
 stat_fields(1,21)= 'TRAC21  '
    stat_fname(1)= 'stats/DIC',
    stat_fname(2)= 'stats/NH4',
    stat_fname(3)= 'stats/NO2',
    stat_fname(4)= 'stats/NO3',
    stat_fname(5)= 'stats/PO4',
    stat_fname(6)= 'stats/SiO2',
    stat_fname(7)= 'stats/FeT',
    stat_fname(8)= 'stats/DOC',
    stat_fname(9)= 'stats/DON',
    stat_fname(10)= 'stats/DOP',
    stat_fname(11)= 'stats/DOFe',
    stat_fname(12)= 'stats/POC',
    stat_fname(13)= 'stats/PON',
    stat_fname(14)= 'stats/POP',
    stat_fname(15)= 'stats/POSi',
    stat_fname(16)= 'stats/POFe',
    stat_fname(17)= 'stats/PIC',
    stat_fname(18)= 'stats/c1',
    stat_fname(19)= 'stats/c2',
    stat_fname(20)= 'stats/c3',
    stat_fname(21)= 'stats/c4',
 &
''')

